server:
  port: 1114
  tomcat:
    uri-encoding: UTF-8
  address: 0.0.0.0
  error:
    whitelabel:
      enabled: true
---

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    username: survey_kotlin
    password: 1234
    url: jdbc:mariadb://localhost:3306/survey_kotlin
    driver-class-name: org.mariadb.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
---

util:
  encrypt:
    secretKey: gdgkfow29fj20fchg95761kjfsd344er
  jwt:
    secretKey: hgff91kfoqiwuejcuzghqpmvzzd34tyui
    refreshKey: hgff91kfoqiwuejcuzghqpmvzzd4tyui
    defaultExpirationMinutes: 60 # 10시간

pattern:
  localDate: yyyy-MM-dd
  localDateTime: yyyy-MM-dd HH:mm:ss

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.seung.survey_kotlin